CREATE TYPE enumUF AS ENUM('AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO');
CREATE TYPE enumGenero AS ENUM('Masculino', 'Feminino', 'Agenero', 'Fluido', 'Outro');
CREATE TYPE enumTipoI AS ENUM('Federal', 'Estadual', 'Particular', 'Internacional', 'Comunitaria');
CREATE TYPE enumAcesso AS ENUM('total', 'direcao', 'comum');
CREATE TYPE enum_areaConhecimento AS ENUM('Ciências Agrárias','Ciências Biológicas','Ciências da Saúde','Ciências Exatas e da Terra','Engenharias','Ciências Humanas','Ciências Sociais Aplicadas','Linguística, Letras e Artes');

-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE Contato (
Id_Contato Integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
Email varchar(255),
Telefone Integer,
Link varchar(255),
Id_Pessoa Integer NOT NULL
);

CREATE TABLE Cidade (
UF enumUF,
Nome varchar(255),
Id_Cidade Integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)
);

CREATE TABLE Pessoa_Endereco (
Endereco_Preferencial boolean,
Id_Endereco Integer,
Id_Pessoa Integer,
PRIMARY KEY(Id_Endereco,Id_Pessoa)
);

CREATE TABLE Participacao_Artefato (
Tipo_Acesso Integer,
Id_Artefato Integer,
Id_Pessoa Integer,
PRIMARY KEY(Id_Artefato,Id_Pessoa)
);

CREATE TABLE Centro (
IdCentro Integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
Nome varchar(255),
Id_Instituicao Integer 
);

CREATE TABLE CEP (
Logradouro varchar(255),
Id_CEP Integer PRIMARY KEY,
Id_Cidade Integer,
FOREIGN KEY(Id_Cidade) REFERENCES Cidade (Id_Cidade)
);

CREATE TABLE Pessoa_Fisica (
Id_PF Integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
Nome_Preferencial varchar(255),
Registro_Geral BigInt,
Genero enumGenero,
Matricula Integer,
CPF BigInt,
Aluno boolean,
Id_Pessoa Integer NOT NULL
);

CREATE TABLE Endereco_Centro (
Id Integer,
Id_Endereco Integer,
PRIMARY KEY(Id,Id_Endereco),
FOREIGN KEY(Id) REFERENCES Centro (IdCentro)
);

CREATE TABLE Instituicao (
IdInstituicao Integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
nomeInstituicao varchar(255),
Tipo enumTipoI
);

CREATE TABLE Cargo (
Nivel_Acesso enumAcesso,
Id_Cargo Integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
nome varchar(255)
);

CREATE TABLE Gestao (
Data_Final date,
Data_Inicio date,
Id_Cargo Integer,
Id_ca Integer,
Id_Pessoa Integer,
PRIMARY KEY(Data_Inicio,Id_Cargo,Id_ca,Id_Pessoa),
FOREIGN KEY(Id_Cargo) REFERENCES Cargo (Id_Cargo)
);

CREATE TABLE Centro_Academico (
Nome varchar(255),
Id_ca Integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
Id_Curso Integer,
Id_Endereco Integer
);

CREATE TABLE Artefato (
Binario bytea,
Link varchar(255),
Publico boolean,
Id_Artefato Integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
Id_Evento Integer
);

CREATE TABLE Tipo_evento (
Nome varchar(255),
Id_tEvento Integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)
);

CREATE TABLE Endereco (
Obs varchar(255),
Numero Integer,
Id_Endereco Integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
Id_CEP Integer,
FOREIGN KEY(Id_CEP) REFERENCES CEP (Id_CEP)
);

CREATE TABLE Pessoa (
Id_Pessoa Integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
data_nascimento date,
Nome varchar(255),
data_cadastro date
);

CREATE TABLE Pessoa_Juridico (
Id_PJ Integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
Id_Pessoa Integer,
CNPJ BigInt,
FOREIGN KEY(Id_Pessoa) REFERENCES Pessoa (Id_Pessoa)
);

CREATE TABLE Evento (
IdEvento Integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
nomeEvento varchar(255),
Data_Fim timestamp,
Data_Inicio timestamp,
Id_tEvento Integer,
Id_Endereco Integer,
FOREIGN KEY(Id_tEvento) REFERENCES Tipo_evento (Id_tEvento),
FOREIGN KEY(Id_Endereco) REFERENCES Endereco (Id_Endereco)
);

CREATE TABLE Tipo_Participao (
Id_Participacao Integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
descricao varchar(255)
);

CREATE TABLE Curso (
nome varchar(255),
Info varchar(255),
Id_Curso Integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
areaConhecimento enum_areaConhecimento,
id_Centro Integer,
FOREIGN KEY(Id_Centro) REFERENCES Centro (IdCentro)
);

CREATE TABLE Evento_Eventos (
Id_Evento Integer,
possui_Id_Evento Integer,
PRIMARY KEY(Id_Evento,possui_Id_Evento),
FOREIGN KEY(Id_Evento) REFERENCES Evento (IdEvento),
FOREIGN KEY(possui_Id_Evento) REFERENCES Evento (IdEvento)
);

CREATE TABLE Evento_CA (
Id_ca Integer,
Id_Evento Integer,
PRIMARY KEY(Id_ca,Id_Evento),
FOREIGN KEY(Id_ca) REFERENCES Centro_Academico (Id_ca),
FOREIGN KEY(Id_Evento) REFERENCES Evento (IdEvento)
);

CREATE TABLE Participa_Evento (
Id_Evento Integer,
Id_Pessoa Integer,
Id_Participacao Integer,
PRIMARY KEY(Id_Evento,Id_Pessoa,Id_Participacao),
FOREIGN KEY(Id_Evento) REFERENCES Evento (IdEvento),
FOREIGN KEY(Id_Pessoa) REFERENCES Pessoa (Id_Pessoa),
FOREIGN KEY(Id_Participacao) REFERENCES Tipo_Participao (Id_Participacao)
);

ALTER TABLE Contato ADD FOREIGN KEY(Id_Pessoa) REFERENCES Pessoa (Id_Pessoa);
ALTER TABLE Pessoa_Endereco ADD FOREIGN KEY(Id_Endereco) REFERENCES Endereco (Id_Endereco);
ALTER TABLE Pessoa_Endereco ADD FOREIGN KEY(Id_Pessoa) REFERENCES Pessoa (Id_Pessoa);
ALTER TABLE Participacao_Artefato ADD FOREIGN KEY(Id_Artefato) REFERENCES Artefato (Id_Artefato);
ALTER TABLE Participacao_Artefato ADD FOREIGN KEY(Id_Pessoa) REFERENCES Pessoa (Id_Pessoa);
ALTER TABLE Centro ADD FOREIGN KEY(Id_Instituicao) REFERENCES Instituicao (IdInstituicao);
ALTER TABLE Pessoa_Fisica ADD FOREIGN KEY(Id_Pessoa) REFERENCES Pessoa (Id_Pessoa);
ALTER TABLE Endereco_Centro ADD FOREIGN KEY(Id_Endereco) REFERENCES Endereco (Id_Endereco);
ALTER TABLE Gestao ADD FOREIGN KEY(Id_ca) REFERENCES Centro_Academico (Id_ca);
ALTER TABLE Gestao ADD FOREIGN KEY(Id_Pessoa) REFERENCES Pessoa (Id_Pessoa);
ALTER TABLE Centro_Academico ADD FOREIGN KEY(Id_Curso) REFERENCES Curso (Id_Curso);
ALTER TABLE Centro_Academico ADD FOREIGN KEY(Id_Endereco) REFERENCES Endereco (Id_Endereco);
ALTER TABLE Artefato ADD FOREIGN KEY(Id_Evento) REFERENCES Evento (IdEvento);

CREATE FUNCTION criarpessoa(data_nasc date, nome varchar(255)) RETURNS Integer AS $$
    DECLARE
    idLocal Integer;
    BEGIN
        INSERT INTO public.pessoa(data_nascimento, nome, data_cadastro)
        VALUES (data_nasc, nome, current_date) RETURNING id_pessoa INTO idLocal;
        RETURN idLocal;
    END; $$
    LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION criarendereco(obs varchar(255), num Integer, logradouro varchar(255), cep Integer, cidadeStr varchar(255)) RETURNS Integer AS $$
    DECLARE
        idLocal Integer;
    BEGIN
        
        INSERT INTO public.cep(logradouro, id_cep, id_cidade)
        VALUES (logradouro, cep, (SELECT id_cidade FROM cidade WHERE nome = cidadeStr));

        INSERT INTO public.endereco( obs, numero,  id_cep)
	    VALUES (obs, num, cep) RETURNING id_endereco INTO idLocal;
        
        RETURN idLocal;
    END; $$
    LANGUAGE PLPGSQL;